version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - MYSQL_DATABASE=pgdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass